/**
 * APIPortal — Interactive API documentation portal.
 *
 * Requirements: 52.1, 52.2, 52.3, 52.4
 *
 * Displays all available endpoints with parameters, response formats,
 * code snippets (Python / JavaScript / R), a "Try It" live query builder,
 * and API usage statistics / rate-limit information.
 */
import React, { useCallback, useMemo, useState } from 'react';
import { GlassPanel } from '../../design-system/GlassPanel';

// ── Types ─────────────────────────────────────────────────────────────────────

type HttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE';

export interface ApiParam {
  name: string;
  type: string;
  required: boolean;
  description: string;
  defaultValue?: string;
  options?: string[];
}

export interface ApiEndpoint {
  id: string;
  method: HttpMethod;
  path: string;
  summary: string;
  description: string;
  queryParams?: ApiParam[];
  bodyParams?: ApiParam[];
  responseFormat: string;
  responseExample: string;
  tag: string;
}

export interface ApiUsageStats {
  totalRequests: number;
  successRate: number;
  avgLatencyMs: number;
  rateLimitPerMinute: number;
  rateLimitPerDay: number;
  requestsToday: number;
}

type Language = 'python' | 'javascript' | 'r';

// ── Endpoint catalogue ────────────────────────────────────────────────────────

export const API_ENDPOINTS: ApiEndpoint[] = [
  {
    id: 'predict',
    method: 'GET',
    path: '/api/predict',
    summary: 'Climate Prediction',
    description:
      'Returns AI-generated 7-day climate predictions (rainfall, temp_max, temp_min) for a specified region and date. Predictions are generated by the VAYU transformer model trained on ERA5 reanalysis data.',
    queryParams: [
      { name: 'date', type: 'string (YYYY-MM-DD)', required: true, description: 'Forecast base date', defaultValue: 'today' },
      { name: 'region', type: 'string', required: false, description: 'Region ID', defaultValue: 'full_india', options: ['full_india', 'western_ghats', 'north_east_india', 'indo_gangetic_plain', 'central_india'] },
      { name: 'lead_day', type: 'integer (1–7)', required: false, description: 'Lead time in days', defaultValue: '1' },
      { name: 'include_uncertainty', type: 'boolean', required: false, description: 'Include uncertainty estimates', defaultValue: 'true' },
    ],
    responseFormat: 'JSON — PredictionResponse with grid_cells array',
    responseExample: `{
  "request_date": "2025-07-15",
  "lead_times": [1, 2, 3, 4, 5, 6, 7],
  "model_version": "vayu-v2",
  "grid_cells": [
    {
      "lat": 18.25, "lon": 73.5, "node_idx": 0,
      "rainfall": 45.2, "temp_max": 32.1, "temp_min": 24.5,
      "rainfall_uncertainty": 8.3,
      "temp_max_uncertainty": 1.2,
      "temp_min_uncertainty": 0.9
    }
  ]
}`,
    tag: 'Core',
  },
  {
    id: 'scenario',
    method: 'POST',
    path: '/api/scenario',
    summary: 'What-If Scenario',
    description:
      'Runs a climate perturbation scenario (temperature offset, rainfall scaling, monsoon delay, SST anomaly) and returns deltas between baseline and scenario grid cells.',
    bodyParams: [
      { name: 'scenario_type', type: 'string', required: true, description: 'Scenario type', options: ['temperature_offset', 'rainfall_scaling', 'monsoon_delay', 'sst_anomaly'] },
      { name: 'magnitude', type: 'number', required: true, description: 'Perturbation magnitude (e.g. +2 for 2°C offset)', defaultValue: '2' },
      { name: 'target_region', type: 'string', required: false, description: 'Region to apply perturbation' },
      { name: 'target_season', type: 'string', required: false, description: 'Season (kharif, rabi, summer, winter)' },
    ],
    responseFormat: 'JSON — ScenarioResponse with baseline, scenario, and delta arrays',
    responseExample: `{
  "scenario_type": "temperature_offset",
  "magnitude": 2,
  "summary": {
    "temp_max": { "avg_delta": 2.0, "max_delta": 2.4, "affected_cells": 150 }
  },
  "hotspots": [{ "node_idx": 42, "delta_value": 2.4, "percentile_rank": 98 }],
  "clamped": false
}`,
    tag: 'Core',
  },
  {
    id: 'historical',
    method: 'GET',
    path: '/api/historical',
    summary: 'Historical Climate Data',
    description:
      'Retrieves historical ERA5 reanalysis records for a bounding box and date range. Supports daily, monthly, and yearly granularity.',
    queryParams: [
      { name: 'start_date', type: 'string (YYYY-MM-DD)', required: true, description: 'Start of date range' },
      { name: 'end_date', type: 'string (YYYY-MM-DD)', required: true, description: 'End of date range' },
      { name: 'variable', type: 'string', required: false, description: 'Climate variable', defaultValue: 'rainfall', options: ['rainfall', 'temp_max', 'temp_min'] },
      { name: 'lat_min', type: 'float', required: false, description: 'South boundary latitude', defaultValue: '8.0' },
      { name: 'lat_max', type: 'float', required: false, description: 'North boundary latitude', defaultValue: '37.0' },
      { name: 'lon_min', type: 'float', required: false, description: 'West boundary longitude', defaultValue: '68.0' },
      { name: 'lon_max', type: 'float', required: false, description: 'East boundary longitude', defaultValue: '97.0' },
    ],
    responseFormat: 'JSON array of HistoricalRecord objects',
    responseExample: `[
  { "date": "2024-07-01", "lat": 18.25, "lon": 73.5, "variable": "rainfall", "value": 52.3 },
  { "date": "2024-07-02", "lat": 18.25, "lon": 73.5, "variable": "rainfall", "value": 18.1 }
]`,
    tag: 'Data',
  },
  {
    id: 'metrics',
    method: 'GET',
    path: '/api/metrics',
    summary: 'Verification Metrics',
    description:
      'Returns model skill scores (R², RMSE, MAE, Bias, Brier Score) for VAYU and NWP baselines over the specified evaluation period.',
    queryParams: [
      { name: 'variable', type: 'string', required: false, description: 'Climate variable to evaluate', defaultValue: 'rainfall' },
      { name: 'region', type: 'string', required: false, description: 'Region ID', defaultValue: 'full_india' },
      { name: 'lead_day', type: 'integer', required: false, description: 'Lead time in days', defaultValue: '1' },
      { name: 'source', type: 'string', required: false, description: 'Model source', defaultValue: 'vayu', options: ['vayu', 'gfs', 'ecmwf', 'persistence'] },
    ],
    responseFormat: 'JSON — MetricsResponse with skill scores',
    responseExample: `{
  "variable": "rainfall", "region": "full_india",
  "r2_score": 0.87, "rmse": 8.3, "mae": 5.1,
  "skill_score": 0.72, "lead_time": "day1"
}`,
    tag: 'Metrics',
  },
  {
    id: 'tiles',
    method: 'GET',
    path: '/api/tiles/{z}/{x}/{y}.png',
    summary: 'Heatmap Tiles',
    description:
      'Serves pre-rendered or dynamically generated 256×256 PNG heatmap tiles for the active climate variable at the requested zoom/tile coordinates.',
    queryParams: [
      { name: 'date', type: 'string (YYYY-MM-DD)', required: true, description: 'Prediction date' },
      { name: 'variable', type: 'string', required: false, description: 'Climate variable', defaultValue: 'rainfall' },
      { name: 'colormap', type: 'string', required: false, description: 'Color scale', defaultValue: 'imd_rain', options: ['imd_rain', 'viridis', 'plasma', 'cividis'] },
      { name: 'opacity', type: 'float (0–1)', required: false, description: 'Tile transparency', defaultValue: '0.8' },
    ],
    responseFormat: 'PNG binary — 256×256 pixels, RGBA',
    responseExample: '<binary PNG data>',
    tag: 'Tiles',
  },
  {
    id: 'current_weather',
    method: 'GET',
    path: '/api/current-weather',
    summary: 'Current Weather',
    description:
      'Returns real-time weather observations from Open-Meteo for a given latitude/longitude pair. Updates every 15 minutes.',
    queryParams: [
      { name: 'lat', type: 'float', required: true, description: 'Latitude (decimal degrees)', defaultValue: '18.25' },
      { name: 'lon', type: 'float', required: true, description: 'Longitude (decimal degrees)', defaultValue: '73.5' },
    ],
    responseFormat: 'JSON — current temperature, humidity, rainfall, wind speed',
    responseExample: `{
  "lat": 18.25, "lon": 73.5,
  "temperature_2m": 29.8, "relative_humidity_2m": 78,
  "precipitation": 2.4, "wind_speed_10m": 12.1
}`,
    tag: 'Live',
  },
  {
    id: 'nwp_baseline',
    method: 'GET',
    path: '/api/nwp-baseline',
    summary: 'NWP Baseline Comparison',
    description:
      'Fetches GFS/ECMWF/ICON forecast data from Open-Meteo for the same grid point and date, enabling side-by-side comparison with VAYU.',
    queryParams: [
      { name: 'lat', type: 'float', required: true, description: 'Latitude', defaultValue: '18.25' },
      { name: 'lon', type: 'float', required: true, description: 'Longitude', defaultValue: '73.5' },
      { name: 'date', type: 'string (YYYY-MM-DD)', required: true, description: 'Forecast date' },
      { name: 'models', type: 'string (comma-separated)', required: false, description: 'NWP models to include', defaultValue: 'gfs,ecmwf' },
    ],
    responseFormat: 'JSON — per-model forecast arrays',
    responseExample: `{
  "lat": 18.25, "lon": 73.5, "date": "2025-07-15",
  "models": { "gfs": { "rainfall": [12.3, 8.1], "temp_max": [33.2, 34.1] } }
}`,
    tag: 'Metrics',
  },
  {
    id: 'health',
    method: 'GET',
    path: '/api/health',
    summary: 'API Health Check',
    description:
      'Returns API and model health status, including model version, uptime, last prediction timestamp, and which regions are currently backed by a real model checkpoint vs. mock data.',
    responseFormat: 'JSON — HealthResponse',
    responseExample: `{
  "status": "ok", "model_loaded": true,
  "model_version": "vayu-v2", "uptime_seconds": 86400,
  "device": "cpu",
  "real_data_regions": ["western_ghats", "central_india"]
}`,
    tag: 'System',
  },
];

// ── Code snippet generators ───────────────────────────────────────────────────

const BASE_URL = 'http://localhost:8000';

export function buildCodeSnippet(
  endpoint: ApiEndpoint,
  paramValues: Record<string, string>,
  language: Language
): string {
  const params = endpoint.queryParams ?? [];
  const queryString = params
    .filter((p) => paramValues[p.name])
    .map((p) => `${p.name}=${encodeURIComponent(paramValues[p.name])}`)
    .join('&');
  const url = `${BASE_URL}${endpoint.path}${queryString ? `?${queryString}` : ''}`;
  const bodyParams = endpoint.bodyParams ?? [];
  const bodyObj: Record<string, string | number> = {};
  bodyParams.forEach((p) => {
    if (paramValues[p.name]) {
      const v = paramValues[p.name];
      bodyObj[p.name] = isNaN(Number(v)) ? v : Number(v);
    }
  });
  const bodyJson = JSON.stringify(bodyObj, null, 2);

  if (language === 'python') {
    if (endpoint.method === 'GET') {
      return `import requests

response = requests.get(
    "${url}",
    timeout=10
)
data = response.json()
print(data)`;
    }
    return `import requests

payload = ${bodyJson}
response = requests.post(
    "${BASE_URL}${endpoint.path}",
    json=payload,
    timeout=30
)
data = response.json()
print(data)`;
  }

  if (language === 'javascript') {
    if (endpoint.method === 'GET') {
      return `const response = await fetch("${url}");
const data = await response.json();
console.log(data);`;
    }
    return `const response = await fetch("${BASE_URL}${endpoint.path}", {
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify(${bodyJson})
});
const data = await response.json();
console.log(data);`;
  }

  // R
  if (endpoint.method === 'GET') {
    return `library(httr)
library(jsonlite)

resp <- GET("${url}")
data <- content(resp, as = "parsed", type = "application/json")
print(data)`;
  }
  return `library(httr)
library(jsonlite)

payload <- ${bodyJson.replace(/"/g, '"')}
resp <- POST(
  "${BASE_URL}${endpoint.path}",
  body = toJSON(payload, auto_unbox = TRUE),
  content_type_json()
)
data <- content(resp, as = "parsed", type = "application/json")
print(data)`;
}

// ── Mock usage stats (replace with real API hook when available) ──────────────

const MOCK_STATS: ApiUsageStats = {
  totalRequests: 142_380,
  successRate: 99.3,
  avgLatencyMs: 87,
  rateLimitPerMinute: 60,
  rateLimitPerDay: 10_000,
  requestsToday: 1_847,
};

// ── Method badge colours ──────────────────────────────────────────────────────

const METHOD_COLORS: Record<HttpMethod, { bg: string; text: string }> = {
  GET: { bg: 'rgba(56, 189, 132, 0.2)', text: '#38bd84' },
  POST: { bg: 'rgba(99, 179, 237, 0.2)', text: '#63b3ed' },
  PUT: { bg: 'rgba(246, 173, 85, 0.2)', text: '#f6ad55' },
  DELETE: { bg: 'rgba(252, 129, 129, 0.2)', text: '#fc8181' },
};

const TAG_COLORS: Record<string, string> = {
  Core: '#9f7aea',
  Data: '#38bd84',
  Metrics: '#63b3ed',
  Tiles: '#f6ad55',
  Live: '#fc8181',
  System: '#718096',
};

// ── Sub-components ────────────────────────────────────────────────────────────

const MethodBadge: React.FC<{ method: HttpMethod }> = ({ method }) => {
  const { bg, text } = METHOD_COLORS[method];
  return (
    <span
      style={{
        display: 'inline-block',
        padding: '2px 8px',
        borderRadius: '4px',
        background: bg,
        color: text,
        fontSize: '11px',
        fontWeight: 700,
        letterSpacing: '0.5px',
        fontFamily: 'monospace',
        flexShrink: 0,
      }}
    >
      {method}
    </span>
  );
};

const TagBadge: React.FC<{ tag: string }> = ({ tag }) => (
  <span
    style={{
      display: 'inline-block',
      padding: '1px 7px',
      borderRadius: '10px',
      background: `${TAG_COLORS[tag] ?? '#718096'}22`,
      color: TAG_COLORS[tag] ?? '#718096',
      fontSize: '10px',
      fontWeight: 600,
      letterSpacing: '0.5px',
    }}
  >
    {tag}
  </span>
);

// ── CodeBlock ─────────────────────────────────────────────────────────────────

interface CodeBlockProps {
  code: string;
  language: Language;
}

const CodeBlock: React.FC<CodeBlockProps> = ({ code, language }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = useCallback(() => {
    navigator.clipboard?.writeText(code).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [code]);

  const langLabel: Record<Language, string> = {
    python: 'Python',
    javascript: 'JavaScript',
    r: 'R',
  };

  return (
    <div
      style={{
        position: 'relative',
        background: 'rgba(0, 0, 0, 0.4)',
        border: '1px solid rgba(255,255,255,0.07)',
        borderRadius: '8px',
        overflow: 'hidden',
      }}
    >
      {/* Header row */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          padding: '6px 12px',
          background: 'rgba(255,255,255,0.04)',
          borderBottom: '1px solid rgba(255,255,255,0.06)',
        }}
      >
        <span style={{ fontSize: '11px', color: 'rgba(255,255,255,0.4)', fontFamily: 'monospace' }}>
          {langLabel[language]}
        </span>
        <button
          onClick={handleCopy}
          title="Copy code"
          style={{
            background: 'none',
            border: '1px solid rgba(255,255,255,0.15)',
            borderRadius: '4px',
            color: copied ? '#38bd84' : 'rgba(255,255,255,0.5)',
            cursor: 'pointer',
            fontSize: '11px',
            padding: '2px 8px',
            transition: 'color 0.2s',
          }}
        >
          {copied ? '✓ Copied' : 'Copy'}
        </button>
      </div>
      <pre
        style={{
          margin: 0,
          padding: '12px 14px',
          fontSize: '12px',
          lineHeight: 1.6,
          color: 'rgba(255,255,255,0.82)',
          fontFamily: '"Fira Code", "Cascadia Code", monospace',
          overflowX: 'auto',
          whiteSpace: 'pre',
        }}
      >
        {code}
      </pre>
    </div>
  );
};

// ── TryItPanel ────────────────────────────────────────────────────────────────

interface TryItPanelProps {
  endpoint: ApiEndpoint;
}

const TryItPanel: React.FC<TryItPanelProps> = ({ endpoint }) => {
  const allParams = [...(endpoint.queryParams ?? []), ...(endpoint.bodyParams ?? [])];
  const defaultValues = useMemo(() => {
    const vals: Record<string, string> = {};
    allParams.forEach((p) => { if (p.defaultValue) vals[p.name] = p.defaultValue; });
    return vals;
  }, [allParams]);

  const [paramValues, setParamValues] = useState<Record<string, string>>(defaultValues);
  const [isLoading, setIsLoading] = useState(false);
  const [response, setResponse] = useState<string | null>(null);
  const [responseStatus, setResponseStatus] = useState<number | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [activeLang, setActiveLang] = useState<Language>('python');

  const snippet = useMemo(
    () => buildCodeSnippet(endpoint, paramValues, activeLang),
    [endpoint, paramValues, activeLang]
  );

  const handleRun = useCallback(async () => {
    setIsLoading(true);
    setResponse(null);
    setError(null);
    setResponseStatus(null);
    try {
      const qp = (endpoint.queryParams ?? [])
        .filter((p) => paramValues[p.name])
        .map((p) => `${p.name}=${encodeURIComponent(paramValues[p.name])}`)
        .join('&');
      const url = `${BASE_URL}${endpoint.path}${qp ? `?${qp}` : ''}`;
      const options: RequestInit = { method: endpoint.method };
      if (endpoint.method === 'POST' && endpoint.bodyParams) {
        const body: Record<string, string | number> = {};
        endpoint.bodyParams.forEach((p) => {
          if (paramValues[p.name]) {
            const v = paramValues[p.name];
            body[p.name] = isNaN(Number(v)) ? v : Number(v);
          }
        });
        options.headers = { 'Content-Type': 'application/json' };
        options.body = JSON.stringify(body);
      }
      const res = await fetch(url, options);
      setResponseStatus(res.status);
      const contentType = res.headers.get('content-type') ?? '';
      if (contentType.includes('application/json')) {
        const data = await res.json();
        setResponse(JSON.stringify(data, null, 2));
      } else {
        setResponse(`[binary response: ${contentType}]`);
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setIsLoading(false);
    }
  }, [endpoint, paramValues]);

  const statusColor = responseStatus
    ? responseStatus < 300
      ? '#38bd84'
      : responseStatus < 500
      ? '#f6ad55'
      : '#fc8181'
    : 'transparent';

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
      {/* Parameter inputs */}
      {allParams.length > 0 && (
        <div>
          <div
            style={{
              fontSize: '11px',
              fontWeight: 600,
              textTransform: 'uppercase',
              letterSpacing: '1px',
              color: 'rgba(255,255,255,0.4)',
              marginBottom: '8px',
            }}
          >
            Parameters
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {allParams.map((param) => (
              <div key={param.name} style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                <div style={{ width: '140px', flexShrink: 0 }}>
                  <div style={{ fontSize: '12px', fontWeight: 600, color: 'rgba(255,255,255,0.8)', fontFamily: 'monospace' }}>
                    {param.name}
                    {param.required && (
                      <span style={{ color: '#fc8181', marginLeft: '3px' }}>*</span>
                    )}
                  </div>
                  <div style={{ fontSize: '10px', color: 'rgba(255,255,255,0.35)', marginTop: '1px' }}>
                    {param.type}
                  </div>
                </div>
                {param.options ? (
                  <select
                    value={paramValues[param.name] ?? ''}
                    onChange={(e) => setParamValues((prev) => ({ ...prev, [param.name]: e.target.value }))}
                    style={{
                      flex: 1,
                      background: 'rgba(0,0,0,0.35)',
                      border: '1px solid rgba(255,255,255,0.12)',
                      borderRadius: '6px',
                      color: 'rgba(255,255,255,0.85)',
                      fontSize: '12px',
                      padding: '5px 8px',
                      outline: 'none',
                    }}
                  >
                    {!param.required && <option value="">— optional —</option>}
                    {param.options.map((o) => (
                      <option key={o} value={o}>{o}</option>
                    ))}
                  </select>
                ) : (
                  <input
                    type="text"
                    placeholder={param.defaultValue ?? ''}
                    value={paramValues[param.name] ?? ''}
                    onChange={(e) => setParamValues((prev) => ({ ...prev, [param.name]: e.target.value }))}
                    style={{
                      flex: 1,
                      background: 'rgba(0,0,0,0.35)',
                      border: '1px solid rgba(255,255,255,0.12)',
                      borderRadius: '6px',
                      color: 'rgba(255,255,255,0.85)',
                      fontSize: '12px',
                      padding: '5px 8px',
                      outline: 'none',
                    }}
                  />
                )}
                <div
                  style={{ fontSize: '11px', color: 'rgba(255,255,255,0.35)', maxWidth: '160px', flexShrink: 0 }}
                  title={param.description}
                >
                  {param.description}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Code snippet tabs */}
      <div>
        <div style={{ display: 'flex', gap: '4px', marginBottom: '8px' }}>
          {(['python', 'javascript', 'r'] as Language[]).map((lang) => (
            <button
              key={lang}
              onClick={() => setActiveLang(lang)}
              style={{
                background: activeLang === lang ? 'rgba(99,179,237,0.2)' : 'rgba(255,255,255,0.06)',
                border: `1px solid ${activeLang === lang ? 'rgba(99,179,237,0.5)' : 'rgba(255,255,255,0.1)'}`,
                borderRadius: '5px',
                color: activeLang === lang ? '#63b3ed' : 'rgba(255,255,255,0.5)',
                cursor: 'pointer',
                fontSize: '11px',
                fontWeight: 600,
                padding: '3px 10px',
                textTransform: lang === 'r' ? 'uppercase' : 'capitalize',
                transition: 'all 0.15s',
              }}
            >
              {lang === 'r' ? 'R' : lang.charAt(0).toUpperCase() + lang.slice(1)}
            </button>
          ))}
        </div>
        <CodeBlock code={snippet} language={activeLang} />
      </div>

      {/* Run button */}
      <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
        <button
          onClick={handleRun}
          disabled={isLoading}
          style={{
            background: isLoading ? 'rgba(99,179,237,0.1)' : 'rgba(99,179,237,0.25)',
            border: '1px solid rgba(99,179,237,0.5)',
            borderRadius: '7px',
            color: '#63b3ed',
            cursor: isLoading ? 'not-allowed' : 'pointer',
            fontSize: '13px',
            fontWeight: 600,
            padding: '7px 20px',
            transition: 'all 0.15s',
          }}
        >
          {isLoading ? '⏳ Running…' : '▶ Try It'}
        </button>
        {responseStatus && (
          <span
            style={{
              fontSize: '12px',
              fontWeight: 600,
              color: statusColor,
              fontFamily: 'monospace',
            }}
          >
            HTTP {responseStatus}
          </span>
        )}
      </div>

      {/* Response area */}
      {(response || error) && (
        <div>
          <div
            style={{
              fontSize: '11px',
              fontWeight: 600,
              textTransform: 'uppercase',
              letterSpacing: '1px',
              color: 'rgba(255,255,255,0.4)',
              marginBottom: '6px',
            }}
          >
            Response
          </div>
          <pre
            style={{
              margin: 0,
              padding: '12px',
              background: error ? 'rgba(252,129,129,0.08)' : 'rgba(0,0,0,0.4)',
              border: `1px solid ${error ? 'rgba(252,129,129,0.25)' : 'rgba(255,255,255,0.07)'}`,
              borderRadius: '8px',
              color: error ? '#fc8181' : 'rgba(255,255,255,0.8)',
              fontSize: '12px',
              fontFamily: '"Fira Code", monospace',
              lineHeight: 1.6,
              maxHeight: '260px',
              overflowY: 'auto',
              overflowX: 'auto',
              whiteSpace: 'pre',
            }}
          >
            {error ?? response}
          </pre>
        </div>
      )}
    </div>
  );
};

// ── EndpointCard ──────────────────────────────────────────────────────────────

interface EndpointCardProps {
  endpoint: ApiEndpoint;
  isOpen: boolean;
  onToggle: () => void;
}

const EndpointCard: React.FC<EndpointCardProps> = ({ endpoint, isOpen, onToggle }) => {
  const [activeTab, setActiveTab] = useState<'docs' | 'try'>('docs');

  return (
    <div
      style={{
        border: '1px solid rgba(255,255,255,0.08)',
        borderRadius: '10px',
        overflow: 'hidden',
        background: isOpen ? 'rgba(255,255,255,0.03)' : 'transparent',
        transition: 'background 0.2s',
      }}
    >
      {/* Accordion header */}
      <button
        onClick={onToggle}
        style={{
          width: '100%',
          background: 'none',
          border: 'none',
          cursor: 'pointer',
          padding: '12px 16px',
          display: 'flex',
          alignItems: 'center',
          gap: '10px',
          textAlign: 'left',
        }}
        aria-expanded={isOpen}
      >
        <MethodBadge method={endpoint.method} />
        <code
          style={{
            flex: 1,
            color: 'rgba(255,255,255,0.85)',
            fontSize: '13px',
            fontFamily: 'monospace',
            fontWeight: 500,
          }}
        >
          {endpoint.path}
        </code>
        <span style={{ fontSize: '12px', color: 'rgba(255,255,255,0.5)', marginRight: '6px' }}>
          {endpoint.summary}
        </span>
        <TagBadge tag={endpoint.tag} />
        <span
          style={{
            marginLeft: '8px',
            color: 'rgba(255,255,255,0.35)',
            fontSize: '14px',
            transform: isOpen ? 'rotate(90deg)' : 'rotate(0deg)',
            transition: 'transform 0.2s',
            display: 'inline-block',
          }}
        >
          ›
        </span>
      </button>

      {/* Expanded content */}
      {isOpen && (
        <div style={{ padding: '0 16px 16px', borderTop: '1px solid rgba(255,255,255,0.06)' }}>
          {/* Tabs */}
          <div style={{ display: 'flex', gap: '4px', margin: '12px 0 14px' }}>
            {(['docs', 'try'] as const).map((tab) => (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                style={{
                  background: activeTab === tab ? 'rgba(255,255,255,0.1)' : 'none',
                  border: `1px solid ${activeTab === tab ? 'rgba(255,255,255,0.2)' : 'transparent'}`,
                  borderRadius: '5px',
                  color: activeTab === tab ? 'rgba(255,255,255,0.9)' : 'rgba(255,255,255,0.4)',
                  cursor: 'pointer',
                  fontSize: '12px',
                  fontWeight: 600,
                  padding: '4px 12px',
                  textTransform: 'capitalize',
                  transition: 'all 0.15s',
                }}
              >
                {tab === 'try' ? '⚡ Try It' : '📄 Docs'}
              </button>
            ))}
          </div>

          {activeTab === 'docs' && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
              {/* Description */}
              <p style={{ margin: 0, fontSize: '13px', color: 'rgba(255,255,255,0.65)', lineHeight: 1.6 }}>
                {endpoint.description}
              </p>

              {/* Query params table */}
              {endpoint.queryParams && endpoint.queryParams.length > 0 && (
                <ParamTable title="Query Parameters" params={endpoint.queryParams} />
              )}
              {endpoint.bodyParams && endpoint.bodyParams.length > 0 && (
                <ParamTable title="Request Body" params={endpoint.bodyParams} />
              )}

              {/* Response format */}
              <div>
                <div style={{ fontSize: '12px', fontWeight: 700, color: 'rgba(255,255,255,0.55)', marginBottom: '6px', textTransform: 'uppercase', letterSpacing: '0.8px' }}>
                  Response Format
                </div>
                <div style={{ fontSize: '12px', color: 'rgba(255,255,255,0.65)', marginBottom: '8px' }}>
                  {endpoint.responseFormat}
                </div>
                <CodeBlock code={endpoint.responseExample} language="javascript" />
              </div>
            </div>
          )}

          {activeTab === 'try' && <TryItPanel endpoint={endpoint} />}
        </div>
      )}
    </div>
  );
};

// ── ParamTable ────────────────────────────────────────────────────────────────

interface ParamTableProps {
  title: string;
  params: ApiParam[];
}

const ParamTable: React.FC<ParamTableProps> = ({ title, params }) => (
  <div>
    <div
      style={{
        fontSize: '12px',
        fontWeight: 700,
        color: 'rgba(255,255,255,0.55)',
        marginBottom: '8px',
        textTransform: 'uppercase',
        letterSpacing: '0.8px',
      }}
    >
      {title}
    </div>
    <div
      style={{
        background: 'rgba(0,0,0,0.3)',
        border: '1px solid rgba(255,255,255,0.07)',
        borderRadius: '8px',
        overflow: 'hidden',
      }}
    >
      {/* Header row */}
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: '120px 160px 60px 1fr',
          gap: '8px',
          padding: '7px 12px',
          background: 'rgba(255,255,255,0.04)',
          borderBottom: '1px solid rgba(255,255,255,0.06)',
          fontSize: '10px',
          fontWeight: 700,
          textTransform: 'uppercase',
          letterSpacing: '0.8px',
          color: 'rgba(255,255,255,0.35)',
        }}
      >
        <span>Name</span>
        <span>Type</span>
        <span>Required</span>
        <span>Description</span>
      </div>
      {params.map((p, i) => (
        <div
          key={p.name}
          style={{
            display: 'grid',
            gridTemplateColumns: '120px 160px 60px 1fr',
            gap: '8px',
            padding: '8px 12px',
            borderBottom: i < params.length - 1 ? '1px solid rgba(255,255,255,0.04)' : 'none',
            fontSize: '12px',
          }}
        >
          <code style={{ color: '#63b3ed', fontFamily: 'monospace', fontSize: '12px' }}>{p.name}</code>
          <span style={{ color: 'rgba(255,255,255,0.5)', fontFamily: 'monospace', fontSize: '11px' }}>
            {p.type}
          </span>
          <span
            style={{
              color: p.required ? '#fc8181' : 'rgba(255,255,255,0.3)',
              fontSize: '11px',
              fontWeight: 600,
            }}
          >
            {p.required ? 'Yes' : 'No'}
          </span>
          <span style={{ color: 'rgba(255,255,255,0.6)' }}>
            {p.description}
            {p.defaultValue && (
              <span style={{ color: 'rgba(255,255,255,0.35)', marginLeft: '4px' }}>
                (default: <code style={{ fontFamily: 'monospace', fontSize: '11px' }}>{p.defaultValue}</code>)
              </span>
            )}
          </span>
        </div>
      ))}
    </div>
  </div>
);

// ── UsageStatsPanel ───────────────────────────────────────────────────────────

const UsageStatsPanel: React.FC<{ stats: ApiUsageStats }> = ({ stats }) => {
  const usagePct = Math.min(100, (stats.requestsToday / stats.rateLimitPerDay) * 100);
  const usageColor = usagePct > 80 ? '#fc8181' : usagePct > 50 ? '#f6ad55' : '#38bd84';

  const statItems = [
    { label: 'Total Requests', value: stats.totalRequests.toLocaleString(), icon: '📊' },
    { label: 'Success Rate', value: `${stats.successRate}%`, icon: '✅' },
    { label: 'Avg Latency', value: `${stats.avgLatencyMs} ms`, icon: '⚡' },
    { label: 'Requests Today', value: stats.requestsToday.toLocaleString(), icon: '📅' },
  ];

  return (
    <GlassPanel padding="lg" className="api-usage-stats">
      <div
        style={{
          fontSize: '11px',
          fontWeight: 700,
          textTransform: 'uppercase',
          letterSpacing: '1.2px',
          color: 'rgba(255,255,255,0.4)',
          marginBottom: '14px',
        }}
      >
        📈 API Usage Statistics
      </div>

      {/* Stat grid */}
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
          gap: '10px',
          marginBottom: '16px',
        }}
      >
        {statItems.map((item) => (
          <div
            key={item.label}
            style={{
              background: 'rgba(255,255,255,0.04)',
              border: '1px solid rgba(255,255,255,0.07)',
              borderRadius: '8px',
              padding: '10px 12px',
            }}
          >
            <div style={{ fontSize: '18px', marginBottom: '4px' }}>{item.icon}</div>
            <div style={{ fontSize: '18px', fontWeight: 700, color: 'rgba(255,255,255,0.9)' }}>
              {item.value}
            </div>
            <div style={{ fontSize: '10px', color: 'rgba(255,255,255,0.4)', marginTop: '2px' }}>
              {item.label}
            </div>
          </div>
        ))}
      </div>

      {/* Rate limit bar */}
      <div>
        <div
          style={{
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            marginBottom: '6px',
          }}
        >
          <span style={{ fontSize: '11px', color: 'rgba(255,255,255,0.5)', fontWeight: 600 }}>
            Daily Rate Limit
          </span>
          <span style={{ fontSize: '11px', color: usageColor, fontWeight: 700 }}>
            {stats.requestsToday.toLocaleString()} / {stats.rateLimitPerDay.toLocaleString()}
          </span>
        </div>
        <div
          style={{
            height: '6px',
            background: 'rgba(255,255,255,0.1)',
            borderRadius: '3px',
            overflow: 'hidden',
          }}
        >
          <div
            style={{
              height: '100%',
              width: `${usagePct}%`,
              background: usageColor,
              borderRadius: '3px',
              transition: 'width 0.4s ease',
            }}
          />
        </div>
        <div style={{ fontSize: '10px', color: 'rgba(255,255,255,0.35)', marginTop: '4px' }}>
          {stats.rateLimitPerMinute} requests/minute · {stats.rateLimitPerDay.toLocaleString()} requests/day
        </div>
      </div>
    </GlassPanel>
  );
};

// ── Main APIPortal component ──────────────────────────────────────────────────

export interface APIPortalProps {
  /** Override API base URL (useful for pointing at production) */
  baseUrl?: string;
  /** Override usage stats (e.g. from a real API hook) */
  usageStats?: ApiUsageStats;
  /** Initial endpoint to expand */
  initialEndpointId?: string;
}

/**
 * APIPortal — Full interactive API documentation portal.
 *
 * Requirements: 52.1, 52.2, 52.3, 52.4
 */
export const APIPortal: React.FC<APIPortalProps> = ({
  usageStats = MOCK_STATS,
  initialEndpointId,
}) => {
  const [openId, setOpenId] = useState<string | null>(initialEndpointId ?? null);
  const [searchQuery, setSearchQuery] = useState('');
  const [activeTag, setActiveTag] = useState<string>('All');

  const tags = useMemo(() => {
    const all = Array.from(new Set(API_ENDPOINTS.map((e) => e.tag)));
    return ['All', ...all];
  }, []);

  const filtered = useMemo(() => {
    const q = searchQuery.toLowerCase();
    return API_ENDPOINTS.filter((e) => {
      const matchesSearch =
        !q ||
        e.path.toLowerCase().includes(q) ||
        e.summary.toLowerCase().includes(q) ||
        e.description.toLowerCase().includes(q);
      const matchesTag = activeTag === 'All' || e.tag === activeTag;
      return matchesSearch && matchesTag;
    });
  }, [searchQuery, activeTag]);

  const handleToggle = useCallback((id: string) => {
    setOpenId((prev) => (prev === id ? null : id));
  }, []);

  return (
    <div
      className="api-portal"
      data-testid="api-portal"
      role="region"
      aria-label="API Documentation Portal"
      style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}
    >
      {/* ── Header ── */}
      <GlassPanel padding="lg" className="api-portal-header">
        <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '16px' }}>
          <div>
            <div
              style={{
                fontSize: '10px',
                fontWeight: 700,
                textTransform: 'uppercase',
                letterSpacing: '1.5px',
                color: 'rgba(99, 179, 237, 0.9)',
                marginBottom: '6px',
              }}
            >
              🔌 VAYU Climate API
            </div>
            <h1
              style={{
                margin: 0,
                fontSize: '22px',
                fontWeight: 700,
                color: 'rgba(255,255,255,0.95)',
                lineHeight: 1.3,
              }}
            >
              API Documentation Portal
            </h1>
            <p
              style={{
                margin: '6px 0 0',
                fontSize: '13px',
                color: 'rgba(255,255,255,0.5)',
                lineHeight: 1.5,
              }}
            >
              Explore all VAYU endpoints, construct queries interactively, and access code
              snippets for Python, JavaScript, and R.
            </p>
          </div>
          <div
            style={{
              background: 'rgba(56,189,132,0.15)',
              border: '1px solid rgba(56,189,132,0.35)',
              borderRadius: '20px',
              padding: '4px 12px',
              fontSize: '11px',
              fontWeight: 700,
              color: '#38bd84',
              whiteSpace: 'nowrap',
              flexShrink: 0,
              alignSelf: 'flex-start',
              marginTop: '2px',
            }}
          >
            ● API v2 · Live
          </div>
        </div>

        {/* Base URL badge */}
        <div
          style={{
            marginTop: '12px',
            background: 'rgba(0,0,0,0.3)',
            border: '1px solid rgba(255,255,255,0.08)',
            borderRadius: '6px',
            padding: '7px 12px',
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
          }}
        >
          <span style={{ fontSize: '10px', fontWeight: 600, textTransform: 'uppercase', color: 'rgba(255,255,255,0.35)', letterSpacing: '0.8px' }}>
            Base URL
          </span>
          <code style={{ fontSize: '12px', color: '#63b3ed', fontFamily: 'monospace' }}>
            {BASE_URL}
          </code>
        </div>
      </GlassPanel>

      {/* ── Usage Stats ── */}
      <UsageStatsPanel stats={usageStats} />

      {/* ── Search + Filter ── */}
      <GlassPanel padding="md" className="api-portal-search">
        <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap', alignItems: 'center' }}>
          <input
            type="search"
            placeholder="Search endpoints…"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            aria-label="Search API endpoints"
            style={{
              flex: '1 1 200px',
              background: 'rgba(0,0,0,0.35)',
              border: '1px solid rgba(255,255,255,0.12)',
              borderRadius: '7px',
              color: 'rgba(255,255,255,0.85)',
              fontSize: '13px',
              padding: '7px 12px',
              outline: 'none',
              minWidth: '160px',
            }}
          />
          <div style={{ display: 'flex', gap: '4px', flexWrap: 'wrap' }}>
            {tags.map((tag) => (
              <button
                key={tag}
                onClick={() => setActiveTag(tag)}
                style={{
                  background: activeTag === tag ? `${TAG_COLORS[tag] ?? '#718096'}33` : 'rgba(255,255,255,0.06)',
                  border: `1px solid ${activeTag === tag ? (TAG_COLORS[tag] ?? '#718096') : 'rgba(255,255,255,0.1)'}`,
                  borderRadius: '5px',
                  color: activeTag === tag ? (TAG_COLORS[tag] ?? '#e2e8f0') : 'rgba(255,255,255,0.4)',
                  cursor: 'pointer',
                  fontSize: '11px',
                  fontWeight: 600,
                  padding: '4px 10px',
                  transition: 'all 0.15s',
                }}
              >
                {tag}
              </button>
            ))}
          </div>
        </div>
      </GlassPanel>

      {/* ── Endpoint list ── */}
      <GlassPanel padding="md" className="api-portal-endpoints">
        <div
          style={{
            fontSize: '11px',
            fontWeight: 700,
            textTransform: 'uppercase',
            letterSpacing: '1.2px',
            color: 'rgba(255,255,255,0.4)',
            marginBottom: '12px',
          }}
        >
          Endpoints ({filtered.length})
        </div>
        {filtered.length === 0 ? (
          <div
            style={{
              textAlign: 'center',
              padding: '32px 0',
              color: 'rgba(255,255,255,0.3)',
              fontSize: '13px',
            }}
          >
            No endpoints match your search.
          </div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
            {filtered.map((endpoint) => (
              <EndpointCard
                key={endpoint.id}
                endpoint={endpoint}
                isOpen={openId === endpoint.id}
                onToggle={() => handleToggle(endpoint.id)}
              />
            ))}
          </div>
        )}
      </GlassPanel>

      {/* ── Authentication note ── */}
      <GlassPanel padding="md" className="api-portal-auth">
        <div
          style={{
            fontSize: '11px',
            fontWeight: 700,
            textTransform: 'uppercase',
            letterSpacing: '1.2px',
            color: 'rgba(255,255,255,0.4)',
            marginBottom: '8px',
          }}
        >
          🔑 Authentication
        </div>
        <p style={{ margin: 0, fontSize: '13px', color: 'rgba(255,255,255,0.6)', lineHeight: 1.6 }}>
          The VAYU API currently operates without authentication for internal dashboard use. For
          external integrations, pass your API key as the{' '}
          <code style={{ fontFamily: 'monospace', color: '#63b3ed', fontSize: '12px' }}>
            X-API-Key
          </code>{' '}
          header. Contact the MAUSAM team for key provisioning.
        </p>
      </GlassPanel>
    </div>
  );
};

export default APIPortal;
